# Generated by Django 4.1.7 on 2023-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='genre',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='nickname',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='most_famous_movie',
            field=models.TextField(null=True),
        ),
    ]
